version: 2
sources:
  - name: scryfall
    database: mtg-dbt-dsone-2026
    schema: mtg_raw
    description: MTG raw cards data
    config:
      freshness:
        warn_after:
          count: 2
          period: day
        error_after:
          count: 3
          period: day
        loaded_at_field: fetched_at
    tables:
      - name: raw_scryfall_cards
        description: Daily bulk data cards from scryfall source
        columns:
          - name: id
            description: uuid of the card json data
            tests:
              - not_null
              - unique
